'use client';
import {FormEvent,useCallback,useEffect,useMemo,useState} from 'react';
import {supabase} from '../../../lib/supabase';
import {fetchBookingClients} from '../../../lib/client-directory';
import NewAppointmentModal,{type BookingResult,type NewAppointmentSeed} from '../../../components/NewAppointmentModal';
import NewClientModal,{type CreatedClient} from '../../../components/NewClientModal';

type Client={id:string;full_name:string;phone:string|null;email:string|null};
type Treatment={id:string;name:string;default_session_count:number;default_duration_minutes:number;catalog_details_pending:boolean};
type TreatmentBranch={treatment_id:string;branch_id:string;is_active:boolean};
type Branch={id:string;name:string};
type Plan={id:string;client_id:string;status:string;treatment_id:string;total_sessions:number;default_branch_id:string|null;allow_branch_change:boolean;created_at:string};
type Session={id:string;plan_id:string;session_number:number;status:string;completed_at:string|null};
type Appointment={id:string;plan_session_id:string;branch_id:string;starts_at:string;ends_at:string;status:string};
const liveStatuses=['pending','confirmed','arrived'];
const dateLabel=(value:string)=>new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeStyle:'short',timeZone:'America/Mexico_City'}).format(new Date(value));
const todayInput=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const sessionOptions=[1,3,5,8,10];
const durationOptions=[15,30,45,60,85];

export default function ClientesPage(){
 const [clients,setClients]=useState<Client[]>([]);const [branches,setBranches]=useState<Branch[]>([]);const[treatments,setTreatments]=useState<Treatment[]>([]);const[treatmentBranches,setTreatmentBranches]=useState<TreatmentBranch[]>([]);const[plans,setPlans]=useState<Plan[]>([]);const[sessions,setSessions]=useState<Session[]>([]);const[appointments,setAppointments]=useState<Appointment[]>([]);
 const [clientId,setClientId]=useState('');const [branchId,setBranchId]=useState('');const[treatmentId,setTreatmentId]=useState('');const [count,setCount]=useState('');const[planDuration,setPlanDuration]=useState('');const[rewardPoints,setRewardPoints]=useState('');const[rewardReason,setRewardReason]=useState('');
 const[error,setError]=useState('');const[success,setSuccess]=useState('');const[saving,setSaving]=useState(false);const[loading,setLoading]=useState(true);
 const[newClientOpen,setNewClientOpen]=useState(false);const[bookingOpen,setBookingOpen]=useState(false);const[bookingPlanId,setBookingPlanId]=useState<string|null>(null);const[bookingTreatmentId,setBookingTreatmentId]=useState<string|null>(null);const[bookingSeed,setBookingSeed]=useState<NewAppointmentSeed>({branchId:'',date:todayInput(),time:'09:00'});
 const reload=useCallback(async()=>{
  setError('');if(!supabase){setError('Falta configurar Supabase.');setLoading(false);return;}setLoading(true);
  const [clientsResult,branchesResult,treatmentsResult,treatmentBranchesResult,plansResult]=await Promise.allSettled([
    fetchBookingClients(),
    supabase.from('branches').select('id,name').eq('is_active',true).order('name'),
    supabase.from('treatments').select('id,name,default_session_count,default_duration_minutes,catalog_details_pending').eq('is_active',true).order('name'),
    supabase.from('treatment_branches').select('treatment_id,branch_id,is_active').eq('is_active',true),
    supabase.from('client_treatment_plans').select('id,client_id,status,treatment_id,total_sessions,default_branch_id,allow_branch_change,created_at').order('created_at',{ascending:false}),
  ]);
  const warnings:string[]=[];let loadedPlans:Plan[]=[];
  if(clientsResult.status==='fulfilled')setClients(clientsResult.value);else warnings.push(clientsResult.reason instanceof Error?clientsResult.reason.message:String(clientsResult.reason));
  if(branchesResult.status==='fulfilled'&&!branchesResult.value.error)setBranches(branchesResult.value.data??[]);else warnings.push('Sucursales: '+(branchesResult.status==='rejected'?String(branchesResult.reason):branchesResult.value.error?.message));
  if(treatmentsResult.status==='fulfilled'&&!treatmentsResult.value.error)setTreatments((treatmentsResult.value.data??[]) as Treatment[]);else warnings.push('Tratamientos: '+(treatmentsResult.status==='rejected'?String(treatmentsResult.reason):treatmentsResult.value.error?.message));
  if(treatmentBranchesResult.status==='fulfilled'&&!treatmentBranchesResult.value.error)setTreatmentBranches((treatmentBranchesResult.value.data??[]) as TreatmentBranch[]);else warnings.push('Disponibilidad de tratamientos: '+(treatmentBranchesResult.status==='rejected'?String(treatmentBranchesResult.reason):treatmentBranchesResult.value.error?.message));
  if(plansResult.status==='fulfilled'&&!plansResult.value.error){loadedPlans=(plansResult.value.data??[]) as Plan[];setPlans(loadedPlans);}else warnings.push('Planes: '+(plansResult.status==='rejected'?String(plansResult.reason):plansResult.value.error?.message));
  let loadedSessions:Session[]=[];
  if(loadedPlans.length){const sr=await supabase.from('treatment_plan_sessions').select('id,plan_id,session_number,status,completed_at').in('plan_id',loadedPlans.map(p=>p.id)).order('session_number');if(sr.error)warnings.push('Sesiones: '+sr.error.message);else{loadedSessions=(sr.data??[]) as Session[];setSessions(loadedSessions);}}
  else setSessions([]);
  if(loadedSessions.length){const ar=await supabase.from('appointments').select('id,plan_session_id,branch_id,starts_at,ends_at,status').in('plan_session_id',loadedSessions.map(s=>s.id)).order('starts_at',{ascending:false});if(ar.error)warnings.push('Citas: '+ar.error.message);else setAppointments((ar.data??[]) as Appointment[]);}else setAppointments([]);
  setError(warnings.join(' | '));setLoading(false);
 },[]);
 useEffect(()=>{void reload();},[reload]);
 const selected=clients.find(c=>c.id===clientId);const selectedTreatment=treatments.find(t=>t.id===treatmentId);
 const selectedPlans=useMemo(()=>plans.filter(p=>p.client_id===clientId),[plans,clientId]);
 const activeTreatmentIds=useMemo(()=>new Set(selectedPlans.filter(p=>p.status==='active'||p.status==='paused').map(p=>p.treatment_id)),[selectedPlans]);
 const availableNewTreatments=useMemo(()=>treatments.filter(t=>!activeTreatmentIds.has(t.id)&&(!branchId||treatmentBranches.some(link=>link.treatment_id===t.id&&link.branch_id===branchId&&link.is_active))),[treatments,activeTreatmentIds,treatmentBranches,branchId]);
 useEffect(()=>{if(treatmentId&&!availableNewTreatments.some(t=>t.id===treatmentId)){setTreatmentId('');setCount('');setPlanDuration('');}},[availableNewTreatments,treatmentId]);
 async function assign(e:FormEvent){e.preventDefault();setError('');setSuccess('');if(!supabase||!clientId||!branchId||!treatmentId)return;if(!count||!planDuration){setError('Selecciona las sesiones y la duración de este plan.');return;}setSaving(true);const{error:err}=await supabase.rpc('admin_assign_treatment_plan',{p_client_id:clientId,p_branch_id:branchId,p_treatment_id:treatmentId,p_total_sessions:Number(count),p_duration_minutes:Number(planDuration)});setSaving(false);if(err){setError(err.message);return;}setSuccess('Tratamiento iniciado con la configuración personalizada del cliente.');setCount('');setPlanDuration('');setTreatmentId('');await reload();}
 async function addRewards(e:FormEvent){e.preventDefault();setError('');setSuccess('');if(!supabase||!clientId)return;setSaving(true);const{error:err}=await supabase.rpc('admin_add_reward_points',{p_client_id:clientId,p_points:Number(rewardPoints),p_description:rewardReason.trim()});setSaving(false);if(err){setError(err.message);return;}setSuccess('Movimiento de rewards registrado.');setRewardPoints('');setRewardReason('');}
 function planInfo(plan:Plan){const ps=sessions.filter(s=>s.plan_id===plan.id);const ids=new Set(ps.map(s=>s.id));const live=appointments.filter(a=>ids.has(a.plan_session_id)&&liveStatuses.includes(a.status)).sort((a,b)=>a.starts_at.localeCompare(b.starts_at))[0]??null;const completed=ps.filter(s=>s.status==='completed').length;const available=ps.find(s=>s.status==='available')??null;return{live,completed,available};}
 function schedule(plan:Plan){const info=planInfo(plan);if(!info.available||info.live)return;const firstBranch=plan.default_branch_id||branches[0]?.id||'';setBookingPlanId(plan.id);setBookingTreatmentId(plan.treatment_id);setBookingSeed({branchId:firstBranch,date:todayInput(),time:'09:00'});setBookingOpen(true);setSuccess('');setError('');}
 return <section className="page-stack"><div className="page-heading client-page-heading"><div><p className="eyebrow">Directorio</p><h2>Clientes</h2><p className="muted">Consulta sus tratamientos activos, agenda la siguiente sesión o inicia un tratamiento diferente.</p></div><button type="button" className="primary-button inline-button" onClick={()=>{setNewClientOpen(true);setError('');setSuccess('');}}>+ Nuevo cliente</button></div>
 {error&&<div className="alert error-alert" role="alert">{error}</div>}{success&&<div className="alert" role="status">{success}</div>}
 {loading?<div className="fullscreen-inline"><div className="spinner"/></div>:<div className="card-grid three-cols">{clients.map(c=><button type="button" onClick={()=>{setClientId(c.id);setTreatmentId('');setCount('');setPlanDuration('');setSuccess('');setError('');}} className="panel-card client-selector-card" key={c.id} data-selected={clientId===c.id}><span className="client-avatar">{c.full_name.slice(0,1).toUpperCase()}</span><div><h3>{c.full_name}</h3><p>{c.phone||'Sin teléfono'}</p><p>{c.email||''}</p><small>Planes: {plans.filter(p=>p.client_id===c.id).length} · Activos: {plans.filter(p=>p.client_id===c.id&&p.status==='active').length}</small></div></button>)}</div>}
 {!loading&&!clients.length&&!error&&<div className="empty-state"><strong>Todavía no hay clientes registrados.</strong><span>Cuando se registren en la app aparecerán aquí.</span></div>}
 {selected&&<div className="client-detail-stack"><section className="panel-card client-profile-head"><div><p className="eyebrow">Cliente seleccionado</p><h2>{selected.full_name}</h2><p className="muted">{selected.phone||'Sin teléfono'}{selected.email?` · ${selected.email}`:''}</p></div><span className="count-badge">{selectedPlans.filter(p=>p.status==='active').length} activos</span></section>
  <section className="panel-card"><div className="section-heading"><div><p className="eyebrow">Continuidad</p><h3>Tratamientos iniciados</h3></div></div>
   {selectedPlans.length?<div className="admin-plan-list">{selectedPlans.map(plan=>{const info=planInfo(plan);const treatment=treatments.find(t=>t.id===plan.treatment_id);const branch=branches.find(b=>b.id===plan.default_branch_id);const canSchedule=plan.status==='active'&&Boolean(info.available)&&!info.live;return <article className="admin-plan-card" key={plan.id}><div className="admin-plan-main"><span className="plan-state">{plan.status==='active'?'EN PROGRESO':plan.status.toUpperCase()}</span><h4>{treatment?.name||'Tratamiento'}</h4><p>{info.completed} de {plan.total_sessions} sesiones completadas{branch?` · Haut ${branch.name}`:''}</p><div className="mini-progress"><span style={{width:`${Math.min(100,(info.completed/Math.max(1,plan.total_sessions))*100)}%`}}/></div></div><div className="admin-plan-action">{info.live?<><small>PRÓXIMA CITA</small><strong>{dateLabel(info.live.starts_at)}</strong></>:canSchedule?<><small>SIGUIENTE</small><strong>Sesión {info.available?.session_number} de {plan.total_sessions}</strong><button type="button" className="primary-button inline-button" onClick={()=>schedule(plan)}>Agendar próxima cita</button></>:plan.status==='paused'?<span className="muted">Plan pausado</span>:info.completed>=plan.total_sessions?<span className="muted">Plan completado</span>:<span className="muted">Finaliza la sesión anterior para habilitar la siguiente.</span>}</div></article>})}</div>:<p className="muted">Sin tratamientos asignados.</p>}
  </section>
  <section className="panel-card"><form onSubmit={assign} className="client-action-form"><div><p className="eyebrow">Nuevo plan</p><h3>Iniciar otro tratamiento</h3><p className="muted">Define aquí las sesiones y la duración reales para este cliente. Los datos de la ficha del tratamiento son solo informativos.</p></div><label>Sucursal<select required value={branchId} onChange={e=>setBranchId(e.target.value)}><option value="">Selecciona sucursal</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Tratamiento<select required value={treatmentId} onChange={e=>{setTreatmentId(e.target.value);setCount('');setPlanDuration('');}}><option value="">Selecciona tratamiento</option>{availableNewTreatments.map(t=><option key={t.id} value={t.id}>{t.name}{t.catalog_details_pending?' · ficha pendiente':''}</option>)}</select>{selectedTreatment&&<small className="plan-reference">Referencia del catálogo: {selectedTreatment.default_session_count} {selectedTreatment.default_session_count===1?'sesión':'sesiones'} · {selectedTreatment.default_duration_minutes} min · puede variar.</small>}{branchId&&availableNewTreatments.length===0&&<small className="muted">No hay otro tratamiento activo disponible en esta sucursal.</small>}</label><div className="plan-config-field"><span>Sesiones de este plan</span><div className="session-choice-row">{sessionOptions.map(option=><button key={option} type="button" className={count===String(option)?'selected':''} aria-pressed={count===String(option)} onClick={()=>setCount(String(option))}>{option}</button>)}</div></div><label>Duración por cita<select required value={planDuration} onChange={e=>setPlanDuration(e.target.value)}><option value="">Selecciona duración</option>{durationOptions.map(option=><option key={option} value={option}>{option} minutos</option>)}</select></label><button className="primary-button inline-button" type="submit" disabled={saving||!availableNewTreatments.length||!treatmentId||!count||!planDuration}>Iniciar tratamiento</button>{!availableNewTreatments.length&&<small className="muted">Este cliente ya tiene activos todos los tratamientos disponibles.</small>}</form></section>
  <section className="panel-card"><form onSubmit={addRewards} className="client-action-form"><div><p className="eyebrow">Lealtad</p><h3>Rewards</h3></div><label>Puntos a agregar (negativo para descontar)<input type="number" min="-100000" max="100000" required value={rewardPoints} onChange={e=>setRewardPoints(e.target.value)}/></label><label>Motivo<input required minLength={3} value={rewardReason} onChange={e=>setRewardReason(e.target.value)} placeholder="Compra, recompensa, ajuste…"/></label><button className="secondary-button inline-button" disabled={saving} type="submit">Registrar movimiento</button></form></section>
 </div>}
 <NewClientModal open={newClientOpen} branches={branches} onClose={()=>setNewClientOpen(false)} onCreated={async(client:CreatedClient)=>{setNewClientOpen(false);await reload();setClientId(client.id);setBranchId(client.branch_id);setTreatmentId('');setCount('');setPlanDuration('');setSuccess(`Cliente agregado correctamente. Enviaremos el correo de bienvenida a ${client.email}.`);}}/>
 <NewAppointmentModal open={bookingOpen} branches={branches} seed={bookingSeed} presetClientId={clientId} presetTreatmentId={bookingTreatmentId} presetPlanId={bookingPlanId} onClose={()=>setBookingOpen(false)} onCreated={(booking:BookingResult)=>{setBookingOpen(false);setSuccess(`Cita creada correctamente · ${booking.cabin_name} · sesión ${booking.session_number} de ${booking.total_sessions}.`);void reload();}}/>
 </section>;
}
