"use client";
import {FormEvent,useEffect,useState} from 'react';
import {supabase} from '../../../lib/supabase';
type Branch={id:string;name:string;address:string|null;phone:string|null;google_review_url:string|null;is_active:boolean}; type Cabin={id:string;branch_id:string;name:string;is_active:boolean};
export default function SucursalesPage(){const[branches,setBranches]=useState<Branch[]>([]);const[cabins,setCabins]=useState<Cabin[]>([]);const[drafts,setDrafts]=useState<Record<string,string>>({});const[reviewDrafts,setReviewDrafts]=useState<Record<string,string>>({});const[loading,setLoading]=useState(true);const[saving,setSaving]=useState('');const[error,setError]=useState('');const[success,setSuccess]=useState('');
 async function load(){if(!supabase)return;setLoading(true);try{const[b,c]=await Promise.all([supabase.from('branches').select('id,name,address,phone,google_review_url,is_active').order('name'),supabase.from('cabins').select('id,branch_id,name,is_active').order('sort_order')]);if(b.error)throw b.error;if(c.error)throw c.error;const rows=(b.data??[]) as Branch[];setBranches(rows);setDrafts(Object.fromEntries(rows.map(x=>[x.id,x.phone??''])));setReviewDrafts(Object.fromEntries(rows.map(x=>[x.id,x.google_review_url??''])));setCabins((c.data??[])as Cabin[])}catch(e){setError(e instanceof Error?e.message:'No se pudieron cargar las sucursales.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function savePhone(e:FormEvent,branch:Branch){e.preventDefault();if(!supabase)return;setSaving(branch.id);setError('');setSuccess('');const{error:err}=await supabase.rpc('admin_update_branch_links',{p_branch_id:branch.id,p_phone:drafts[branch.id]??'',p_google_review_url:reviewDrafts[branch.id]??''});setSaving('');if(err){setError(err.message);return;}setSuccess(`Datos de contacto de ${branch.name} actualizados.`);await load();}
 return <section className="page-stack"><div className="page-heading"><p className="eyebrow">Operación</p><h2>Sucursales y cabinas</h2><p className="muted">Configura el WhatsApp de cada sucursal y su enlace directo para dejar una reseña en Google.</p></div>{error&&<div className="alert error-alert">{error}</div>}{success&&<div className="alert">{success}</div>}{loading?<div className="fullscreen-inline"><div className="spinner"/></div>:branches.length?<div className="card-grid three-cols">{branches.map(b=>{const branchCabins=cabins.filter(c=>c.branch_id===b.id);return <article className="panel-card branch-card" key={b.id}><div className="section-heading"><div><p className="eyebrow">{b.is_active?'Activa':'Inactiva'}</p><h3>{b.name}</h3></div><span className="count-badge">{branchCabins.length}</span></div><p className="muted">{b.address||'Dirección pendiente'}</p><form className="branch-contact-form" onSubmit={e=>void savePhone(e,b)}><label>WhatsApp de la sucursal<input value={drafts[b.id]??''} onChange={e=>setDrafts(current=>({...current,[b.id]:e.target.value}))} placeholder="+52 442 000 0000" inputMode="tel"/><small>Se usa cuando un cliente solicita su próxima sesión desde la app.</small></label><label>Enlace para reseña en Google<input type="url" value={reviewDrafts[b.id]??''} onChange={e=>setReviewDrafts(current=>({...current,[b.id]:e.target.value}))} placeholder="https://g.page/r/.../review"/><small>Pega el enlace de “Escribir una reseña” de la ficha de Google de esta sucursal.</small></label><button className="secondary-button inline-button" disabled={saving===b.id}>{saving===b.id?'Guardando…':'Guardar contacto y reseña'}</button></form><div className="cabin-list">{branchCabins.length?branchCabins.map(c=><span key={c.id}>{c.name}</span>):<small>Sin cabinas registradas</small>}</div></article>})}</div>:<div className="empty-state large-empty"><strong>No hay sucursales registradas.</strong><span>Agrega las sucursales reales en Supabase.</span></div>}</section>}
