'use client';
import {useMemo,useState} from 'react';
import {MobileShell} from '@/components/MobileShell';
import {useClient} from '@/components/ClientProvider';
import {TreatmentTile} from '@/components/TreatmentTile';
import {Icon} from '@/components/Icon';
const CATALOG_CATEGORIES=['depilacion-laser','corporales','faciales'] as const;
export default function TreatmentsPage(){const {data}=useClient();const [category,setCategory]=useState('all');const [search,setSearch]=useState('');
 const allowedCategories=useMemo(()=>CATALOG_CATEGORIES.map(slug=>data?.categories.find(c=>c.slug===slug)).filter((c):c is NonNullable<typeof c>=>Boolean(c)),[data?.categories]);
 const items=useMemo(()=>data?.treatments.filter(t=>(category==='all'||(category==='featured'?t.is_featured:t.category_id===category))&&t.name.toLocaleLowerCase('es-MX').includes(search.trim().toLocaleLowerCase('es-MX')))??[],[data?.treatments,category,search]);
 return <MobileShell title="Tratamientos" eyebrow="EXPLORA · HAUT CLINICAL"><div className="catalog-intro"><span className="eyebrow">CUIDADO PERSONALIZADO</span><h2>Encuentra tu momento de cuidado.</h2><p>Descubre los tratamientos de HAUT. Nuestro equipo puede orientarte sobre cada opción.</p></div><label className="catalog-search"><Icon name="search" size={20}/><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Busca un tratamiento" aria-label="Buscar tratamientos"/>{search&&<button onClick={()=>setSearch('')} type="button" aria-label="Borrar búsqueda">×</button>}</label><div className="chips" role="group" aria-label="Filtrar tratamientos"><button type="button" onClick={()=>setCategory('all')} aria-pressed={category==='all'} className={`chip ${category==='all'?'active':''}`}>Todos</button><button type="button" onClick={()=>setCategory('featured')} aria-pressed={category==='featured'} className={`chip ${category==='featured'?'active':''}`}><Icon name="star" size={14}/> Favoritos</button>{allowedCategories.map(c=><button type="button" key={c.id} aria-pressed={category===c.id} className={`chip ${category===c.id?'active':''}`} onClick={()=>setCategory(c.id)}>{c.name}</button>)}</div><div className="catalog-count"><span>{items.length} {items.length===1?'tratamiento':'tratamientos'}</span><span>HAUT CLINICAL CENTER</span></div>{items.length?<div className="catalog-grid">{items.map(t=><TreatmentTile key={t.id} treatment={t}/>)}</div>:<div className="empty-feature compact"><Icon name="search" size={25}/><h3>No encontramos resultados</h3><p>Prueba otra búsqueda o elige una categoría diferente.</p><button type="button" className="secondary-button" onClick={()=>{setSearch('');setCategory('all')}}>Mostrar todos</button></div>}</MobileShell>}
