'use client';import {FormEvent,useState,useEffect} from 'react';import Link from 'next/link';import {MobileShell} from '@/components/MobileShell';import {useClient} from '@/components/ClientProvider';import {supabase} from '@/lib/supabase';
export default function ProfilePage(){const {session,data,refresh,signOut}=useClient();const [editing,setEditing]=useState(false);const [name,setName]=useState('');const [phone,setPhone]=useState('');const [branch,setBranch]=useState('');const [error,setError]=useState('');const [success,setSuccess]=useState('');const [saving,setSaving]=useState(false);
 useEffect(()=>{setName(data?.profile?.full_name??'');setPhone(data?.profile?.phone??'');setBranch(data?.profile?.preferred_branch_id??'');},[data?.profile]);
 async function save(e:FormEvent){e.preventDefault();setError('');setSuccess('');if(!supabase)return;if(name.trim().length<2||phone.replace(/\D/g,'').length<10||!branch){setError('Revisa tu nombre, teléfono y sucursal.');return;}setSaving(true);const result=await supabase.from('profiles').update({full_name:name.trim(),phone:phone.trim(),preferred_branch_id:branch}).eq('id',session.user.id);setSaving(false);if(result.error)setError(result.error.message);else {setEditing(false);setSuccess('Datos actualizados.');await refresh();}}
 return <MobileShell title="Mi perfil"><article className="card"><h3>{data?.profile?.full_name||'Mi cuenta'}</h3><p>{session.user.email}</p><p>{data?.profile?.phone||'Sin teléfono'}</p><p>Mi sucursal: {data?.branches.find(b=>b.id===data.profile?.preferred_branch_id)?.name||'Sin sucursal'}</p></article>
 {success&&<p className="form-success">{success}</p>}{error&&<p className="form-error">{error}</p>}
 {editing?<form className="card edit-form" onSubmit={save}><label>Nombre<input value={name} required onChange={e=>setName(e.target.value)}/></label><label>Teléfono<input type="tel" required value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>Mi sucursal<select required value={branch} onChange={e=>setBranch(e.target.value)}><option value="">Selecciona una sucursal</option>{data?.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><button className="primary-button" disabled={saving}>{saving?'Guardando…':'Guardar cambios'}</button><button type="button" className="secondary-button" onClick={()=>setEditing(false)}>Cancelar</button></form>:<button className="secondary-button" onClick={()=>setEditing(true)}>Editar mis datos</button>}
 <div className="section-title"><h2>Mi cuenta</h2></div><div className="card profile-list"><Link href="/rewards">Mis rewards <span>›</span></Link><Link href="/mis-tratamientos">Mis tratamientos <span>›</span></Link><Link href="/mis-citas">Mis citas <span>›</span></Link></div><button className="secondary-button" onClick={()=>void signOut()}>Cerrar sesión</button></MobileShell>;
}
