import Link from 'next/link';
import type {ClientData,Plan} from '@/lib/types';
import {completedCount,dateLabel,treatmentFor,upcomingForPlan,statusLabel} from '@/lib/client-data';
import {Icon} from './Icon';
export function PlanCard({plan,d}:{plan:Plan;d:ClientData}){
 const completed=completedCount(d,plan);const upcoming=upcomingForPlan(d,plan);const t=treatmentFor(d,plan);const total=Math.max(1,plan.total_sessions);const available=d.sessions.find(s=>s.plan_id===plan.id&&s.status==='available');
 const nextCopy=completed===plan.total_sessions?'Plan completado':available?'Solicita tu próxima cita':'Tu próxima sesión se habilitará pronto';
 return <article className="plan-premium"><Link href={`/mis-tratamientos/${plan.id}`} className="plan-head">{t?.image_url?<img src={t.image_url} alt="" loading="lazy"/>:<div className="plan-photo-fallback"><Icon name="sparkles" size={24}/></div>}<span className="plan-heading"><small>PLAN DE TRATAMIENTO</small><strong>{t?.name??'Tratamiento'}</strong><span>{statusLabel(plan.status)}</span></span><Icon name="forward" size={18}/></Link><div className="plan-body"><div className="plan-progress-top"><span>Tu progreso</span><strong>{completed} <span>/ {plan.total_sessions}</span></strong></div><div className="progress-track" role="progressbar" aria-label="Progreso del tratamiento" aria-valuenow={completed} aria-valuemin={0} aria-valuemax={total}><div className="progress-fill" style={{width:`${Math.min(100,completed/total*100)}%`}}/></div><p>{completed===plan.total_sessions?'Todas tus sesiones han finalizado':`${Math.max(0,plan.total_sessions-completed)} sesiones por completar`}</p><div className="plan-bottom">{upcoming?<span className="plan-next"><Icon name="calendar" size={16}/> {dateLabel(upcoming.starts_at)}</span>:<span className="plan-next"><Icon name={available?'chat':'info'} size={16}/> {nextCopy}</span>}<Link href={upcoming?`/mis-citas/${upcoming.id}`:`/mis-tratamientos/${plan.id}`} className="round-next" aria-label={upcoming?'Ver próxima cita':'Ver tratamiento'}><Icon name="arrow" size={18}/></Link></div></div></article>
}
