'use client';
import Link from 'next/link';import {useParams} from 'next/navigation';import {useState} from 'react';
import {MobileShell} from '@/components/MobileShell';import {useClient} from '@/components/ClientProvider';
import {appointmentRequestWhatsappHref,completedCount,dateLabel,justDate,statusLabel,treatmentFor,upcomingForPlan} from '@/lib/client-data';import {BackLink} from '@/components/BackLink';import {Icon} from '@/components/Icon';
const weekdays=['lunes','martes','miércoles','jueves','viernes','sábado','domingo'];
export default function PlanDetail(){const {planId}=useParams<{planId:string}>();const {data}=useClient();const [weekday,setWeekday]=useState('lunes');const plan=data?.plans.find(p=>p.id===planId);
 if(!data||!plan)return <MobileShell title="Mi tratamiento"><BackLink href="/mis-tratamientos" label="Mis tratamientos"/><div className="empty-card">{data?'No encontramos este plan.':'Cargando…'}</div></MobileShell>;
 const t=treatmentFor(data,plan);const completed=completedCount(data,plan);const upcoming=upcomingForPlan(data,plan);const total=Math.max(1,plan.total_sessions);
 const planSessions=data.sessions.filter(s=>s.plan_id===plan.id&&s.status!=='voided').sort((a,b)=>a.session_number-b.session_number);const available=planSessions.find(s=>s.status==='available')??null;const scheduled=planSessions.find(s=>s.status==='scheduled')??null;
 const branchId=plan.default_branch_id??data.profile?.preferred_branch_id??null;const branch=data.branches.find(b=>b.id===branchId);const requestHref=available&&branch&&t?appointmentRequestWhatsappHref({profileName:data.profile?.full_name,treatmentName:t.name,branchName:branch.name,branchPhone:branch.phone,weekday,sessionNumber:available.session_number,totalSessions:plan.total_sessions}):null;
 const sessionStatus=completed>=plan.total_sessions?'completed':upcoming?'upcoming':available?'request':scheduled?'scheduled':'waiting';
 return <MobileShell title="Mi tratamiento" eyebrow="MI SEGUIMIENTO · HAUT"><BackLink href="/mis-tratamientos" label="Mis tratamientos"/><div className="plan-detail-hero">{t?.image_url?<img src={t.image_url} alt=""/>:<div className="plan-detail-visual"><Icon name="sparkles" size={28}/></div>}<div className="plan-detail-caption"><span className="eyebrow">TU PLAN PERSONAL</span><h2>{t?.name||'Tratamiento'}</h2><span className="pill">{statusLabel(plan.status)}</span></div></div><section className="plan-overview"><div className="plan-progress-top"><span>SESIONES REALIZADAS</span><strong>{completed} <span>/ {plan.total_sessions}</span></strong></div><div className="progress-track" role="progressbar" aria-label="Sesiones completadas" aria-valuemin={0} aria-valuenow={completed} aria-valuemax={total}><div className="progress-fill" style={{width:`${100*completed/total}%`}}/></div><p>{Math.max(0,plan.total_sessions-completed)} sesiones pendientes</p><div className="plan-fact-grid"><div><small>FECHA DE INICIO</small><strong>{justDate(plan.started_at??plan.created_at)}</strong></div><div><small>SUCURSAL</small><strong>Haut {branch?.name??'Por definir'}</strong></div></div></section>
 <div className="section-title"><div><small>TU AGENDA</small><h2>Próxima sesión</h2></div></div>
 {upcoming?<Link className="next-session" href={`/mis-citas/${upcoming.id}`}><span className="next-session-icon"><Icon name="calendar" size={22}/></span><span><small>PRÓXIMA VISITA</small><strong>{dateLabel(upcoming.starts_at,true)}</strong><em>Ver detalle de la cita</em></span><Icon name="forward" size={19}/></Link>:
 sessionStatus==='request'?<section className="appointment-request-card"><div className="appointment-request-icon"><Icon name="calendar" size={24}/></div><div className="appointment-request-copy"><span className="eyebrow">SESIÓN {available?.session_number} DE {plan.total_sessions}</span><h3>Solicita tu próxima cita</h3><p>Elige el día de la semana que prefieres y escríbenos. HAUT {branch?.name??''} te confirmará qué fechas y horarios están disponibles.</p><label><span>Día preferido</span><select value={weekday} onChange={e=>setWeekday(e.target.value)}>{weekdays.map(day=><option key={day} value={day}>{day.charAt(0).toUpperCase()+day.slice(1)}</option>)}</select></label>{requestHref?<a className="whatsapp-request-button" href={requestHref} target="_blank" rel="noreferrer"><Icon name="chat" size={18}/> Solicitar cita por WhatsApp</a>:<div className="request-contact-missing"><strong>Falta el WhatsApp de esta sucursal</strong><span>Pide a HAUT que configure el número de {branch?.name??'tu sucursal'} para habilitar esta solicitud.</span></div>}</div></section>:
 <div className="empty-feature compact"><Icon name="calendar" size={23}/><h3>{sessionStatus==='completed'?'Has completado tu plan':sessionStatus==='scheduled'?'Tu sesión está pendiente de confirmación':'Tu siguiente sesión aún no está habilitada'}</h3><p>{sessionStatus==='completed'?'Puedes consultar todas tus sesiones a continuación.':sessionStatus==='scheduled'?'Cuando la cita esté disponible aparecerá aquí con su fecha y hora.':'La siguiente sesión se habilita después de que HAUT finalice la anterior.'}</p></div>}
 <div className="section-title"><div><small>EL RECORRIDO</small><h2>Mis sesiones</h2></div><span className="sessions-count">{completed}/{plan.total_sessions}</span></div><div className="session-timeline">{planSessions.map(s=>{const ap=data.appointments.filter(a=>a.plan_session_id===s.id).sort((a,b)=>b.starts_at.localeCompare(a.starts_at));const live=ap.find(a=>['pending','confirmed','arrived'].includes(a.status));const last=live||ap.find(a=>a.status==='completed');return <div className={`session ${s.status==='completed'?'done':''}`} key={s.id}><div className="session-number">{s.status==='completed'?<Icon name="check" size={16}/>:String(s.session_number).padStart(2,'0')}</div><div className="session-copy"><strong>Sesión {s.session_number}</strong><span>{s.completed_at?justDate(s.completed_at):last?dateLabel(last.starts_at):s.status==='locked'?'Disponible después de la sesión anterior':statusLabel(s.status)}</span>{last&&<Link className="session-view-link" href={`/mis-citas/${last.id}`}>Ver cita <Icon name="forward" size={14}/></Link>}</div><span className={`session-status ${s.status==='completed'?'is-done':''}`}>{statusLabel(s.status)}</span></div>})}</div></MobileShell>;
}
