'use client';
import {useParams} from 'next/navigation';import Link from 'next/link';
import {MobileShell} from '@/components/MobileShell';import {useClient} from '@/components/ClientProvider';
import {currency,whatsappHref} from '@/lib/client-data';
import {Icon} from '@/components/Icon';import {BackLink} from '@/components/BackLink';
export default function TreatmentDetail(){const {treatmentId}=useParams<{treatmentId:string}>();const {data}=useClient();const t=data?.treatments.find(t=>t.id===treatmentId);
 if(!data)return <MobileShell title="Tratamiento"><div className="empty-card">Cargando información…</div></MobileShell>;
 if(!t)return <MobileShell title="Tratamiento"><BackLink href="/tratamientos" label="Catálogo"/><div className="empty-card">No encontramos este tratamiento.</div></MobileShell>;
 const phone=data.branches.find(b=>b.id===data.profile?.preferred_branch_id)?.phone;const whatsapp=whatsappHref(t.name,phone);const assigned=data.plans.find(p=>p.treatment_id===t.id&&['active','paused'].includes(p.status));
 return <MobileShell title="Conoce tu tratamiento" eyebrow="HAUT · TRATAMIENTOS"><BackLink href="/tratamientos" label="Explorar tratamientos"/><div className="treatment-detail-visual">{t.image_url?<img src={t.image_url} alt={t.name}/>:<div className="detail-photo-empty"><Icon name="image" size={32}/><span>Fotografía próximamente</span></div>}<span className="detail-visual-tag">HAUT · CLINICAL CENTER</span></div><div className="detail-intro"><span className="eyebrow">TU EXPERIENCIA HAUT</span><h2 className="detail-title">{t.name}</h2><p>{t.short_description||'Un tratamiento para conocer con el acompañamiento del equipo HAUT.'}</p></div><div className="detail-facts"><div><Icon name="calendar" size={20}/><span>Sesiones</span><strong>{t.catalog_details_pending?'Por confirmar':t.default_session_count}</strong></div><div><Icon name="clock" size={20}/><span>Duración</span><strong>{t.catalog_details_pending?'Por confirmar':`${t.default_duration_minutes} min`}</strong></div><div><Icon name="info" size={20}/><span>Inversión</span><strong>{t.catalog_details_pending?'Consultar':currency(t.base_price)}</strong></div></div><section className="detail-section"><div className="detail-section-heading"><span className="eyebrow">01 · EL TRATAMIENTO</span><h3>Conócelo mejor</h3></div><p>{t.description||'Nuestro equipo puede orientarte sobre los detalles, cuidados y disponibilidad de este tratamiento.'}</p></section>{t.recommendations&&<section className="detail-section"><div className="detail-section-heading"><span className="eyebrow">02 · A TENER EN CUENTA</span><h3>Recomendaciones</h3></div><p>{t.recommendations}</p></section>}{t.contraindications&&<section className="detail-section"><div className="detail-section-heading"><span className="eyebrow">CUIDADO PERSONALIZADO</span><h3>Consideraciones</h3></div><p>{t.contraindications}</p></section>}<div className="detail-branch"><span className="detail-branch-icon"><Icon name="pin" size={20}/></span><div><strong>Atención en nuestras sucursales</strong><p>Pregunta por la disponibilidad de este tratamiento en tu sucursal HAUT.</p></div></div><div className="detail-sticky-actions">{whatsapp?<a href={whatsapp} className="primary-button" target="_blank" rel="noopener noreferrer"><Icon name="chat" size={19}/> Solicitar información <Icon name="arrow" size={17}/></a>:<div className="empty-card">Haut aún no ha configurado un número de WhatsApp para consultas.</div>}{assigned&&<Link className="secondary-button" href={`/mis-tratamientos/${assigned.id}`}>Ver mi tratamiento asignado <Icon name="forward" size={17}/></Link>}<p className="small-print">La programación de citas se realiza directamente con el equipo de HAUT.</p></div></MobileShell>;
}
