'use client';
import {FormEvent,useEffect,useState} from 'react';
import {supabase} from '../../../lib/supabase';
import {Icon} from '../../../components/Icon';
type Promo={id:string;title:string;description:string|null;image_url:string|null;treatment_id:string|null;is_active:boolean;created_at:string};
type Treatment={id:string;name:string};
const allowedTypes=['image/jpeg','image/png','image/webp','image/avif'];
export default function PromocionesPage(){
 const [rows,setRows]=useState<Promo[]>([]);const[treatments,setTreatments]=useState<Treatment[]>([]);
 const[title,setTitle]=useState('');const[description,setDescription]=useState('');const[imageUrl,setImageUrl]=useState('');const[treatmentId,setTreatmentId]=useState('');const[file,setFile]=useState<File|null>(null);const[preview,setPreview]=useState<string|null>(null);const[showForm,setShowForm]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);
 useEffect(()=>{if(!file){setPreview(null);return;}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file]);
 async function load(){if(!supabase)return;const [promos,catalog]=await Promise.all([supabase.from('promotions').select('id,title,description,image_url,treatment_id,is_active,created_at').order('created_at',{ascending:false}),supabase.from('treatments').select('id,name').eq('is_active',true).order('name')]);if(promos.error)setError(promos.error.message);else setRows(promos.data??[]);if(catalog.error)setError(catalog.error.message);else setTreatments(catalog.data??[]);}
 useEffect(()=>{void load();},[]);
 function chooseFile(next:File|null){if(!next){setFile(null);return;}if(!allowedTypes.includes(next.type)){setError('Elige una imagen JPG, PNG, WebP o AVIF.');return;}if(next.size>10*1024*1024){setError('La imagen no puede superar 10 MB.');return;}setError('');setFile(next);}
 async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;setBusy(true);setError('');setMessage('');try{
  let url=imageUrl.trim()||null;
  if(file){const ext=({'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/avif':'avif'} as Record<string,string>)[file.type];const path=`promotions/${crypto.randomUUID()}.${ext}`;const upload=await supabase.storage.from('treatment-images').upload(path,file,{contentType:file.type,upsert:false,cacheControl:'3600'});if(upload.error)throw upload.error;url=supabase.storage.from('treatment-images').getPublicUrl(path).data.publicUrl;}
  const result=await supabase.from('promotions').insert({title:title.trim(),description:description.trim()||null,image_url:url,treatment_id:treatmentId||null,is_active:true});if(result.error)throw result.error;
  setTitle('');setDescription('');setImageUrl('');setTreatmentId('');setFile(null);setShowForm(false);setMessage('Promoción publicada. Ya está disponible para los clientes autorizados.');await load();
 }catch(cause){setError(cause instanceof Error?cause.message:'No se pudo publicar la promoción.');}finally{setBusy(false);}}
 async function toggle(p:Promo){if(!supabase)return;setError('');const {error:e}=await supabase.from('promotions').update({is_active:!p.is_active}).eq('id',p.id);if(e)setError(e.message);else await load();}
 return <section className="page-stack promotions-admin-page"><div className="treatment-list-heading"><div><p className="eyebrow">COMUNICACIÓN CON CLIENTES</p><h2>Promociones</h2><p className="muted">Lo que publiques aquí se mostrará en el carrusel de Inicio del cliente, según las reglas de visibilidad de Supabase.</p></div><button type="button" className="primary-button" onClick={()=>{setShowForm(v=>!v);setError('');setMessage('')}}>{showForm?'Cerrar formulario':'+ Nueva promoción'}</button></div>
 {error&&<div className="alert error-alert" role="alert">{error}</div>}{message&&<div className="alert success-alert" role="status">{message}</div>}
 {showForm&&<form onSubmit={submit} className="panel-card promotion-editor"><div className="section-heading"><div><p className="eyebrow">NUEVA PROMOCIÓN</p><h3>Comparte una novedad con tus clientes</h3></div><button type="button" className="secondary-button" onClick={()=>setShowForm(false)}>Cancelar</button></div><div className="promotion-form-grid"><div className="promotion-form-fields"><label>Título de la promoción<input required maxLength={150} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Nombre de la promoción"/></label><label>Descripción<textarea rows={4} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Cuéntale al cliente qué incluye…"/></label><label>Tratamiento relacionado (opcional)<select value={treatmentId} onChange={e=>setTreatmentId(e.target.value)}><option value="">Promoción general · Ver promociones</option>{treatments.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><p className="muted promotion-note">Si eliges un tratamiento, el carrusel llevará a su ficha. De lo contrario abrirá Promociones.</p></div><div className="promotion-upload-side"><span className="editor-section-label">IMAGEN DEL CARRUSEL</span><div className="promotion-preview">{preview||imageUrl?<img src={preview||imageUrl} alt="Vista previa de la promoción"/>:<div><Icon name="image" size={28}/><span>Agrega una imagen para el carrusel</span></div>}</div><label className="editor-upload">Seleccionar fotografía<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={e=>chooseFile(e.target.files?.[0]??null)}/></label><label>O utilizar URL de imagen<input type="url" placeholder="https://..." value={imageUrl} onChange={e=>setImageUrl(e.target.value)}/></label><small>JPG, PNG, WebP o AVIF · hasta 10 MB.</small></div></div><div className="editor-footer"><button className="primary-button" type="submit" disabled={busy}>{busy?'Publicando…':'Publicar promoción'}</button></div></form>}
 <div className="promotion-list-admin">{rows.length?rows.map(p=><article className="promotion-admin-card" key={p.id}><div className="promotion-admin-image">{p.image_url?<img src={p.image_url} alt="" loading="lazy"/>:<Icon name="image" size={25}/>}</div><div className="promotion-admin-text"><span className={`mini-pill ${p.is_active?'active-pill':''}`}>{p.is_active?'Publicada':'Oculta'}</span><h3>{p.title}</h3><p className="muted">{p.description||'Sin descripción'}</p>{p.treatment_id&&<small>Enlace a tratamiento relacionado</small>}</div><button type="button" className="secondary-button" onClick={()=>void toggle(p)}>{p.is_active?'Ocultar':'Activar'}</button></article>):<div className="empty-state large-empty"><strong>Aún no hay promociones.</strong><span>Crea tu primera promoción y aparecerá en Inicio cuando esté publicada.</span></div>}</div></section>;
}
