'use client';
import Link from 'next/link';import {useParams} from 'next/navigation';import {useCallback,useEffect,useState} from 'react';
import {formatMoney,getAppointmentViews,statusLabel,type AppointmentView} from '../../../../lib/admin-data';
import {supabase} from '../../../../lib/supabase';
export default function AppointmentDetailPage(){const {appointmentId}=useParams<{appointmentId:string}>();const[a,setA]=useState<AppointmentView|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[success,setSuccess]=useState('');
 const load=useCallback(async()=>{try{const rows=await getAppointmentViews({appointmentId,limit:1});setA(rows[0]??null);}catch(e){setError(e instanceof Error?e.message:'No pudimos cargar esta cita.');}finally{setLoading(false);}},[appointmentId]);
 useEffect(()=>{void load();},[load]);
 async function changeStatus(status:'confirmed'|'arrived'|'completed'|'cancelled'|'no_show'){
  if(!supabase||!a)return;if(['completed','cancelled','no_show'].includes(status)&&!window.confirm(`¿Confirmas que quieres marcar esta cita como «${statusLabel(status)}»?`))return;
  setBusy(true);setError('');setSuccess('');const{error:e}=await supabase.rpc('admin_set_appointment_status',{p_appointment_id:a.id,p_status:status});setBusy(false);if(e){setError(e.message);return;}setSuccess(`Cita: ${statusLabel(status)}. La app del cliente reflejará este cambio al actualizarse.`);await load();}
 if(loading)return <div className="fullscreen-inline"><div className="spinner"/><span>Cargando cita…</span></div>;
 if(!a)return <div className="empty-state large-empty"><strong>Cita no encontrada.</strong><Link href="/citas">Volver a citas</Link></div>;
 const start=new Date(a.startsAt),end=new Date(a.endsAt);const active=['pending','confirmed','arrived'].includes(a.status);
 return <section className="page-stack"><div><Link className="back-link" href="/citas">← Volver a citas</Link></div><section className="detail-hero"><div><p className="eyebrow">Cita</p><h2>{a.clientName}</h2><p>{a.treatmentName}{a.totalSessions&&a.totalSessions>1?` · Sesión ${a.sessionNumber} de ${a.totalSessions}`:''}</p></div><span className={`status-chip status-${a.status}`}>{statusLabel(a.status)}</span></section>
 {error&&<div className="alert error-alert" role="alert">{error}</div>}{success&&<div className="alert" role="status">{success}</div>}
 <div className="detail-grid"><article className="panel-card"><h3>Fecha y ubicación</h3><dl className="detail-list"><div><dt>Fecha</dt><dd>{start.toLocaleDateString('es-MX',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'America/Mexico_City'})}</dd></div><div><dt>Horario</dt><dd>{start.toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit',timeZone:'America/Mexico_City'})} – {end.toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit',timeZone:'America/Mexico_City'})}</dd></div><div><dt>Sucursal</dt><dd>{a.branchName}</dd></div><div><dt>Cabina</dt><dd>{a.cabinName}</dd></div></dl></article><article className="panel-card"><h3>Pago</h3><dl className="detail-list"><div><dt>Estado</dt><dd>{a.paymentStatus}</dd></div><div><dt>Total esperado</dt><dd>{formatMoney(a.amountExpected)}</dd></div><div><dt>Pagado</dt><dd>{formatMoney(a.amountPaid)}</dd></div></dl></article></div>
 {active&&<article className="panel-card"><h3>Gestionar cita</h3><p className="muted">Finalizar actualizará el progreso y habilitará la siguiente sesión del plan. Cancelar o marcar No asistió no suma una sesión.</p><div style={{display:'flex',gap:10,flexWrap:'wrap'}}>{a.status==='pending'&&<button disabled={busy} onClick={()=>void changeStatus('confirmed')}>Confirmar</button>}{a.status!=='arrived'&&<button disabled={busy} onClick={()=>void changeStatus('arrived')}>Marcar llegada</button>}<button disabled={busy} onClick={()=>void changeStatus('completed')}>Finalizar sesión</button><button disabled={busy} onClick={()=>void changeStatus('cancelled')}>Cancelar cita</button><button disabled={busy} onClick={()=>void changeStatus('no_show')}>No asistió</button></div></article>}
 </section>;
}
